brent:test_brent.cpp
	g++ -o test_brent test_brent.cpp -lgsl -lgslcblas
bisection:test_bisection.cpp
	g++ -o test_bisection test_bisection.cpp -lgsl -lgslcblas
newton:test_newton.cpp
	g++ -o test_newton test_newton.cpp -lgsl -lgslcblas
secant:test_secant.cpp
	g++ -o test_secant test_secant.cpp -lgsl -lgslcblas


